version: '2'
services:
  server:
    build:
      context: .
      dockerfile: ./Backend.Dockerfile
    links:
      - db
    ports:
     - 4561:4561
    environment:
      DATABASE_URL: "postgresql://prodbreakers:MannCoTabetai@db:5432/prodbreakers?schema=public"
    volumes:
      - ../backend:/srv/prodBreakers
      - vods:/var/vods
    logging:
      options:
       max-size: "1g"
  stream_server:
    build:
      context: .
      dockerfile: ./Stream.Dockerfile
    ports:
     - 1935:1935
     - 8000:8000
    volumes:
      - ../streamServer:/srv/prodBreakers-stream
      - vods:/srv/vods
    links:
      - server
    logging:
      options:
       max-size: "1g"
  adminer:
    links:
      - db
    image: adminer
    ports:
      - 3739:8080
  db:
    image: postgres:12
    ports:
      - 5432
    environment:
      POSTGRES_DATABASE: "prodbreakers"
      POSTGRES_PASSWORD: MannCoTabetai
      POSTGRES_USER: prodbreakers
    volumes:
      - ./db_setup.sh:/docker-entrypoint-initdb.d/init-uuid.sh
    logging:
      options:
       max-size: "1g"
  webui:
    links:
      - server
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    volumes:
      - ../frontend:/srv/prodBreakers
    stdin_open: true
    logging:
      options:
       max-size: "1g"
  proxy:
    build:
      context: ./
      dockerfile: Nginx.Dockerfile
    ports:
      - 3000:3000
    links:
      - webui
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - vods:/var/vods
volumes:
  vods: